# -*- coding: utf-8 -*-
"""streamlitclass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MeieT8t_QB7u6VytvyxfRqUEI38Kjy2-
"""

try:
  import streamlit as st
except ModuleNotFoundError:
  import os
  os.system("pip install streamlit")
  import streamlit as st

try:
  import pandas as pd
  import plotly.express as px
except ModuleNotFoundError:
  import os
  os.system("pip install pandas plotly")
  import pandas as pd
  import plotly.express as px

#show admin stuff
st.title("Advertising Effectiveness Dashboard - Chris Hesse")
st.sidebar.header("Filters")
x_var=st.sidebar.selectbox("x-axis",['TV','radio','newspaper'])
y_var=st.sidebar.selectbox("y-axis",['sales'])
#show scatter plot
fig=px.scatter(df,x=x_var,y=y_var,trendline='ols')
st.plotly_chart(fig)
#show data frame
st.write('## Data Frame')
st.dataframe(df)

#lets show map
st.title (" I am MAP!!")
fif=px.scatter_mapbox(df,lat='latitude',lon='longitude',color='sales',size='TV', hover_name='City')
fig.update_layout(mapbox_style="carto-positron")
st.plotly_chart(fif)

import pandas as pd

df = pd.read_csv('/content/Advertising_F.csv')
display(df.head())